# demo案例

name: demo

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/**'
      - '__test__/**'
      - 'src/**'
jobs:
  test1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # 步骤1：使用第三方action, 拉取最新代码git pull
      - name: Use Node.js # 步骤2：使用第三方sction，安装nodejs 14 版本
        uses: actions/setup-node@v1
        with: 
          node-version: 14
      - name: print node version # 步骤3：打印node版本以及输出内容
        run: | 
          node -v
          npm -v
          echo 'hello github action'
  test2:
    runs-on: ubuntu-latest
    steps:
      - run: touch a.txt
      - run: echo 100 > a.txt
      - run: cat a.txt