# demo案例

name: test

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/**'
      - '__test__/**'
      - 'src/**'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # 步骤1：使用第三方action, 拉取最新代码git pull
      - name: Use Node.js # 步骤2：使用第三方sction，安装nodejs 14 版本
        uses: actions/setup-node@v1
        with: 
          node-version: 14
      - name: lint and test # 步骤3：安装依赖，执行eslint和单元测试
        run: | 
          npm i
          npm run lint
          npm run test:remote